### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by sschnug** [fabianp/pysofia#3]
Hi,

i tried to install pysofia and it never worked.
I tried all combinations of the following:
- python 2 / 3.4 / 3.5
- pip install / git install

The installation process does not complain (Ubuntu-based system).

But trying usage:

Python 2 reports: ```ImportError: No module named enum```
Python 3 reports: ```ImportError: No module named 'sofia_ml'```

Any idea what i'm doing wrong?

```import pysofia.train_sgd``` is enough to make the code reporting errors.

**Comment by fabianp** [comment]
there are some renaming to do as the module was previously called sofia_ml . Patches welcomed!

**Comment by fabianp** [comment]
I updated it to python3 and made a bunch of fixed, this should be solved

**Comment by sschnug** [comment]
Does it work for you?

No matter if py2 or py3; it doesn't work for me (in freshly installed environments).
This applies to test.py or just importing something like ```from pysofia.compat import RankSVM, RankSVMCV```

Output is always: 

    ImportError: No module named _sofia_ml

**Comment by rth** [comment]
@sschnug Could you please confirm whether the PR above fixed the installation problem for you ? Thanks.

**Comment by sschnug** [comment]
Yes. Install worked last time i tested it. Thanks!
