### ISSUE TITLE
Different results for same data

### ISSUE THREAD

**Issue by vinid** [fabianp/pysofia#4]
Hi, I'm testing pysofia and I've seen that each time it process the same data I get always different results. Is this something related to an inner random number generator or non linearities in the data? results are really different one from each other. Here is the code:

```

from sklearn.cross_validation import ShuffleSplit
from sklearn.grid_search import GridSearchCV
from pysofia.compat import RankSVM
import numpy as np
import time

n_samples, n_features = 50, 20
X = np.random.randn(n_samples, n_features)
w = np.random.randn(n_features)
y = (X.dot(w) + np.random.randn(n_samples)).astype(np.int)

while True:
    rs = RankSVM(max_iter=2000)
    cv = ShuffleSplit(X.shape[0], n_iter=100, test_size=0.2, random_state=0)
    classifier = GridSearchCV(estimator=rs, param_grid={"alpha": [-1, 4, 5]},  cv=cv)
    classifier.fit(X, y)

    rank = classifier.best_estimator_

    print rank.rank(X)

    time.sleep(2)

```

Thank you very much

**Comment by fabianp** [comment]
Yes, the sofia_ml library (which is used by this project) uses its own random number generator so it is not unlikely that you get slightly different results

**Comment by fabianp** [comment]
Try with more data (n_samples = 500 or more) which should give more stable results
